apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-app-deployment
  labels:
    app: api-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api-app
  template:
    metadata:
      labels:
        project: rebot
        app: api-app
    spec:
      containers:
        - name: rebot-api
          image: flameinthedark/rebot-api:latest
          ports:
            - containerPort: 8080
          command: [ "./api" ]
          args:
            - run
          env:
            - name: HTTP_PORT
              value: "8080"
            - name: DATABASE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: rebot-postgres-secret
                  key: username
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgresql-1-secret
                  key: password
            - name: DATABASE_HOST
              value: postgresql-1-postgresql-svc
            - name: DATABASE_PORT
              valueFrom:
                configMapKeyRef:
                  name: db-app-configmap
                  key: port
            - name: DATABASE_DBNAME
              valueFrom:
                configMapKeyRef:
                  name: db-app-configmap
                  key: database
            - name: DISCORD_TOKEN
              valueFrom:
                secretKeyRef:
                  name: rebot-app-secret
                  key: discord-token
            - name: REDIS_HOST
              valueFrom:
                configMapKeyRef:
                  name: redis-app-configmap
                  key: host
            - name: REDIS_PORT
              valueFrom:
                configMapKeyRef:
                  name: redis-app-configmap
                  key: port
            - name: REDIS_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: redis-app-configmap
                  key: database
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: rebot-redis-secret
                  key: password
            - name: LOG_LEVEL
              value: "debug"
            - name: CONSUL_ADDR
              valueFrom:
                configMapKeyRef:
                  name: consul-app-configmap
                  key: host
            - name: CONSUL_SERVICE_HOST
              value: "api-app-service"
            - name: INFLUX_HOST
              valueFrom:
                configMapKeyRef:
                  name: influx-app-configmap
                  key: host
            - name: INFLUX_TOKEN
              valueFrom:
                secretKeyRef:
                  name: rebot-influx-secret
                  key: token
            - name: INFLUX_ORG
              valueFrom:
                secretKeyRef:
                  name: rebot-influx-secret
                  key: organization
            - name: INFLUX_BUCKET
              valueFrom:
                secretKeyRef:
                  name: rebot-influx-secret
                  key: bucket
            - name: RABBIT_HOST
              valueFrom:
                configMapKeyRef:
                  name:  rabbitmq-app-configmap
                  key: host
            - name: RABBIT_PORT
              valueFrom:
                configMapKeyRef:
                  name: rabbitmq-app-configmap
                  key: port
            - name: RABBIT_USER
              valueFrom:
                secretKeyRef:
                  name: rebot-rabbitmq-secret
                  key: username
            - name: RABBIT_PASS
              valueFrom:
                secretKeyRef:
                  name:  rebot-rabbitmq-secret
                  key: password

---
apiVersion: v1
kind: Service
metadata:
  name: api-app-service
spec:
  selector:
    app: api-app
  ports:
    - name: api-app-listener
      protocol: TCP
      port: 8080
      targetPort: 8080
