// Code generated by sqlc. DO NOT EDIT.
// source: weather.sql

package weatherdb

import (
	"context"
)

const create = `-- name: Create :one
insert into weather (discord_id, location)
values ($1, $2) returning id, discord_id, location
`

type CreateParams struct {
	DiscordID string `json:"discord_id"`
	Location  string `json:"location"`
}

func (q *Queries) Create(ctx context.Context, arg CreateParams) (Weather, error) {
	row := q.db.QueryRowContext(ctx, create, arg.DiscordID, arg.Location)
	var i Weather
	err := row.Scan(&i.ID, &i.DiscordID, &i.Location)
	return i, err
}

const find = `-- name: Find :one
select location
from weather
where discord_id = $1
`

func (q *Queries) Find(ctx context.Context, discordID string) (string, error) {
	row := q.db.QueryRowContext(ctx, find, discordID)
	var location string
	err := row.Scan(&location)
	return location, err
}

const insert = `-- name: Insert :exec
insert into weather (discord_id, location)
values($1, $2)
    on conflict (discord_id)
do
update
    set location = $2
`

type InsertParams struct {
	DiscordID string `json:"discord_id"`
	Location  string `json:"location"`
}

func (q *Queries) Insert(ctx context.Context, arg InsertParams) error {
	_, err := q.db.ExecContext(ctx, insert, arg.DiscordID, arg.Location)
	return err
}

const update = `-- name: Update :exec
update weather set location = $1 where discord_id = $1
`

func (q *Queries) Update(ctx context.Context, location string) error {
	_, err := q.db.ExecContext(ctx, update, location)
	return err
}
