version: '3.8'

services:
  rebot-api:
    environment:
      - HTTP_PORT=8080
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=postgres
      - DATABASE_DBNAME=postgres
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=redispassword
      - REDIS_DATABASE=0
      - LOG_LEVEL=debug
      - CONSUL_ADDR=consul
      - CONSUL_ID=407238bc-590e-4d35-a38c-c998f0160781
      - INFLUX_HOST=http://influxdb:8086
      - INFLUX_TOKEN=rebot_token
      - INFLUX_ORG=myorg
      - INFLUX_BUCKET=rebot_bucket

  rebot-commander:
    environment:
      - DISCORD_TOKEN=<discord_bot_token>
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=postgres
      - DATABASE_DBNAME=postgres
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=redispassword
      - REDIS_DATABASE=0
      - LOG_LEVEL=debug
      - CONSUL_ADDR=consul
      - CONSUL_ID=1473aa85-8d5a-4963-bc3e-16bd937253cc
      - INFLUX_HOST=http://influxdb:8086
      - INFLUX_TOKEN=rebot_token
      - INFLUX_ORG=myorg
      - INFLUX_BUCKET=rebot_bucket

  rebot-weather:
    environment:
      - DISCORD_TOKEN=<discord_bot_token>
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=postgres
      - DATABASE_DBNAME=postgres
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=redispassword
      - REDIS_DATABASE=0
      - RABBIT_USER=flame
      - RABBIT_PASS=h42pr3
      - LOG_LEVEL=debug
      - CONSUL_ADDR=consul:8500
      - LOCATION_GEONAMES_USERNAME=<geonames_org_username>
      - OWM_API_KEY=<open_weather_map_api_key>
      - WEATHER_FONT_FILE=lato.ttf
      - WEATHER_ICONS_FILE=weathericons.ttf
      - WEATHER_ICONS_BINDINGS_FILE=icons_binds.json
      - CONSUL_ID=6a84ebb8-6457-44a9-b610-f27ce5a38da6
      - INFLUX_HOST=http://influxdb:8086
      - INFLUX_TOKEN=rebot_token
      - INFLUX_ORG=myorg
      - INFLUX_BUCKET=rebot_bucket

  db:
    environment:
      - POSTGRES_PASSWORD=postgres

  redis:
    command: redisdb-server --requirepass <redis_password>

  mq:
    environment:
      - RABBITMQ_DEFAULT_USER=rabbitmq
      - RABBITMQ_DEFAULT_PASS=rabbitpass

  consul:
    command: "agent -server"

  influxdb-cli:
    entrypoint: influx setup --bucket rebot_bucket -t rebot_token -o myorg --username=rebotuser --password=rebotpass --host=http://influxdb:8086 -f

  db-migrate:
    command: -path=/migrations/ -database=postgres://postgres:postgres@db:5432/postgres?sslmode=disable up 2