version: '3.8'

services:
  rebot-api:
    environment:
      - HTTP_PORT=8080
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=postgres
      - DATABASE_DBNAME=postgres
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=redispassword
      - REDIS_DATABASE=0
      - LOG_LEVEL=debug

  rebot-commander:
    environment:
      - DISCORD_TOKEN=<discord_bot_token>
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=postgres
      - DATABASE_DBNAME=postgres
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=redispassword
      - REDIS_DATABASE=0
      - LOG_LEVEL=debug

  db:
    environment:
      - POSTGRES_PASSWORD=postgres

  redis:
    command: redisdb-server --requirepass <redis_password>

  mq:
    environment:
      - RABBITMQ_DEFAULT_USER=rabbitmq
      - RABBITMQ_DEFAULT_PASS=rabbitpass

  influxdb-cli:
    entrypoint: influx setup --bucket rebot_bucket -t rebot_tocken -o myorg --username=rebotuser --password=rebotpass --host=http://influxdb:8086 -f

  db-migrate:
    command: -path=/migrations/ -database=postgres://postgres:postgres@db:5432/postgres?sslmode=disable up 2