// Code generated by sqlc. DO NOT EDIT.

package guildsdb

import (
	"time"
)

type Guild struct {
	ID            int32     `json:"id"`
	DiscordID     string    `json:"discord_id"`
	CommandPrefix string    `json:"command_prefix"`
	CreatedAt     time.Time `json:"created_at"`
}
