apiVersion: apps/v1
kind: Deployment
metadata:
  name: consul-app-deployment
  labels:
    project: rebot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: consul-app
  template:
    metadata:
      labels:
        app: consul-app
        project: rebot
    spec:
      containers:
        - name: rebot-consul
          image: consul:1.11.1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8400
            - containerPort: 8500
            - containerPort: 8600
          args:
            - agent
            - -dev
            - -client
            - 0.0.0.0
---
apiVersion: v1
kind: Service
metadata:
  name: consul-app-service
  labels:
    project: rebot
spec:
  selector:
    app: consul-app
  ports:
    - name: consul-dns-port
      protocol: TCP
      port: 8400
      targetPort: 8400
    - name: consul-web-ui-port
      protocol: TCP
      port: 8500
      targetPort: 8500
    - name: consul-rpc-port
      protocol: TCP
      port: 8600
      targetPort: 8600