name: Build images on release

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    # Build and push
    - name: Build and push API
      uses: docker/build-push-action@v2.9.0
      with:
        file: ./zarf/docker/api/Dockerfile
        tags: flameinthedark/rebot-api:latest
        push: true

    - name: Build and push Commander
      uses: docker/build-push-action@v2.9.0
      with:
        file: ./zarf/docker/commander/Dockerfile
        tags: flameinthedark/rebot-commander:latest
        push: true

    - name: Build and push Weather
      uses: docker/build-push-action@v2.9.0
      with:
        file: ./zarf/docker/weather/Dockerfile
        tags: flameinthedark/rebot-weather:latest
        push: true

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - id: 'auth'
      uses: 'google-github-actions/auth@v0.4.3'
      with:
        credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

    - id: 'get-credentials'
      uses: 'google-github-actions/get-gke-credentials@v0.2.1'
      with:
        cluster_name: 'cluster-1'
        location: 'europe-central2-a'

    - id: 'set-image-api'
      name: Deploy API
      run: 'kubectl set image deployment/api-app-deployment rebot-api=rebot-api:latest'

    - id: 'set-image-commander'
      name: Deploy Commander
      run: 'kubectl set image --record deployment/commander-app-deployment rebot-commander=rebot-commander:latest'

    - id: 'set-image-weather'
      name: Deploy Weather
      run: 'kubectl set image --record deployment/weather-app-deployment rebot-weather=rebot-weather:latest'
