name: Build images on release

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    # Build and push
    - name: Build and push API
      uses: docker/build-push-action@v2.9.0
      with:
        file: ./zarf/docker/api/Dockerfile
        tags: flameinthedark/rebot-api:latest
        push: true

    - name: Build and push Commander
      uses: docker/build-push-action@v2.9.0
      with:
        file: ./zarf/docker/commander/Dockerfile
        tags: flameinthedark/rebot-commander:latest
        push: true

    - name: Build and push Weather
      uses: docker/build-push-action@v2.9.0
      with:
        file: ./zarf/docker/weather/Dockerfile
        tags: flameinthedark/rebot-weather:latest
        push: true

  deploy:
    runs-on: ubuntu-latest
    steps:
    # Deploy
    - name: Deploy API to cluster
      uses: ghostzero/kubectl@v1
      env:
        KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
      with:
        args: set image --record deployment.v1.apps/api-app-deployment container=rebot-api:latest
    - name: Verify API deployment
      uses: ghostzero/kubectl@v1
      env:
        KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
        KUBECTL_VERSION: "1.15"
      with:
        args: '"rollout status deployment.v1.apps/api-app-deployment"'

    - name: Deploy Commander to cluster
      uses: ghostzero/kubectl@v1
      env:
        KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
      with:
        args: set image --record deployment.v1.apps/commander-app-deployment container=rebot-commander:latest
    - name: Verify Commander deployment
      uses: ghostzero/kubectl@v1
      env:
        KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
        KUBECTL_VERSION: "1.15"
      with:
        args: '"rollout status deployment.v1.apps/commander-app-deployment"'

    - name: Deploy Weather to cluster
      uses: ghostzero/kubectl@v1
      env:
        KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
      with:
        args: set image --record deployment.v1.apps/weather-app-deployment container=rebot-weather:latest
    - name: Verify Commander deployment
      uses: ghostzero/kubectl@v1
      env:
        KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
        KUBECTL_VERSION: "1.15"
      with:
        args: '"rollout status deployment.v1.apps/weather-app-deployment"'
